/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CallingConventions {
    #[serde(rename = "Standard")]
    Standard,
    #[serde(rename = "VarArgs")]
    VarArgs,
    #[serde(rename = "Any")]
    Any,
    #[serde(rename = "HasThis")]
    HasThis,
    #[serde(rename = "ExplicitThis")]
    ExplicitThis,

}

impl ToString for CallingConventions {
    fn to_string(&self) -> String {
        match self {
            Self::Standard => String::from("Standard"),
            Self::VarArgs => String::from("VarArgs"),
            Self::Any => String::from("Any"),
            Self::HasThis => String::from("HasThis"),
            Self::ExplicitThis => String::from("ExplicitThis"),
        }
    }
}

impl Default for CallingConventions {
    fn default() -> CallingConventions {
        Self::Standard
    }
}




