/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ComponentMetadata {
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "allowedHttpHosts", skip_serializing_if = "Option::is_none")]
    pub allowed_http_hosts: Option<Vec<String>>,
    #[serde(rename = "keyValueStores", skip_serializing_if = "Option::is_none")]
    pub key_value_stores: Option<Vec<String>>,
    #[serde(rename = "databases", skip_serializing_if = "Option::is_none")]
    pub databases: Option<Vec<String>>,
}

impl ComponentMetadata {
    pub fn new() -> ComponentMetadata {
        ComponentMetadata {
            description: None,
            allowed_http_hosts: None,
            key_value_stores: None,
            databases: None,
        }
    }
}


