/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomAttributeNamedArgument {
    #[serde(rename = "memberInfo", skip_serializing_if = "Option::is_none")]
    pub member_info: Option<Box<crate::models::MemberInfo>>,
    #[serde(rename = "typedValue", skip_serializing_if = "Option::is_none")]
    pub typed_value: Option<Box<crate::models::CustomAttributeTypedArgument>>,
    #[serde(rename = "memberName", skip_serializing_if = "Option::is_none")]
    pub member_name: Option<String>,
    #[serde(rename = "isField", skip_serializing_if = "Option::is_none")]
    pub is_field: Option<bool>,
}

impl CustomAttributeNamedArgument {
    pub fn new() -> CustomAttributeNamedArgument {
        CustomAttributeNamedArgument {
            member_info: None,
            typed_value: None,
            member_name: None,
            is_field: None,
        }
    }
}


