/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomAttributeData {
    #[serde(rename = "attributeType", skip_serializing_if = "Option::is_none")]
    pub attribute_type: Option<Box<crate::models::Type>>,
    #[serde(rename = "constructor", skip_serializing_if = "Option::is_none")]
    pub constructor: Option<Box<crate::models::ConstructorInfo>>,
    #[serde(rename = "constructorArguments", skip_serializing_if = "Option::is_none")]
    pub constructor_arguments: Option<Vec<crate::models::CustomAttributeTypedArgument>>,
    #[serde(rename = "namedArguments", skip_serializing_if = "Option::is_none")]
    pub named_arguments: Option<Vec<crate::models::CustomAttributeNamedArgument>>,
}

impl CustomAttributeData {
    pub fn new() -> CustomAttributeData {
        CustomAttributeData {
            attribute_type: None,
            constructor: None,
            constructor_arguments: None,
            named_arguments: None,
        }
    }
}


