/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomAttributeTypedArgument {
    #[serde(rename = "argumentType", skip_serializing_if = "Option::is_none")]
    pub argument_type: Option<Box<crate::models::Type>>,
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<serde_json::Value>>,
}

impl CustomAttributeTypedArgument {
    pub fn new() -> CustomAttributeTypedArgument {
        CustomAttributeTypedArgument {
            argument_type: None,
            value: None,
        }
    }
}


