/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Exception {
    #[serde(rename = "targetSite", skip_serializing_if = "Option::is_none")]
    pub target_site: Option<Box<crate::models::MethodBase>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "innerException", skip_serializing_if = "Option::is_none")]
    pub inner_exception: Option<Box<crate::models::Exception>>,
    #[serde(rename = "helpLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub help_link: Option<Option<String>>,
    #[serde(rename = "source", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source: Option<Option<String>>,
    #[serde(rename = "hResult", skip_serializing_if = "Option::is_none")]
    pub h_result: Option<i32>,
    #[serde(rename = "stackTrace", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stack_trace: Option<Option<String>>,
}

impl Exception {
    pub fn new() -> Exception {
        Exception {
            target_site: None,
            message: None,
            data: None,
            inner_exception: None,
            help_link: None,
            source: None,
            h_result: None,
            stack_trace: None,
        }
    }
}


