/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FieldInfo {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "declaringType", skip_serializing_if = "Option::is_none")]
    pub declaring_type: Option<Box<crate::models::Type>>,
    #[serde(rename = "reflectedType", skip_serializing_if = "Option::is_none")]
    pub reflected_type: Option<Box<crate::models::Type>>,
    #[serde(rename = "module", skip_serializing_if = "Option::is_none")]
    pub module: Option<Box<crate::models::Module>>,
    #[serde(rename = "customAttributes", skip_serializing_if = "Option::is_none")]
    pub custom_attributes: Option<Vec<crate::models::CustomAttributeData>>,
    #[serde(rename = "isCollectible", skip_serializing_if = "Option::is_none")]
    pub is_collectible: Option<bool>,
    #[serde(rename = "metadataToken", skip_serializing_if = "Option::is_none")]
    pub metadata_token: Option<i32>,
    #[serde(rename = "memberType", skip_serializing_if = "Option::is_none")]
    pub member_type: Option<crate::models::MemberTypes>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<crate::models::FieldAttributes>,
    #[serde(rename = "fieldType", skip_serializing_if = "Option::is_none")]
    pub field_type: Option<Box<crate::models::Type>>,
    #[serde(rename = "isInitOnly", skip_serializing_if = "Option::is_none")]
    pub is_init_only: Option<bool>,
    #[serde(rename = "isLiteral", skip_serializing_if = "Option::is_none")]
    pub is_literal: Option<bool>,
    #[serde(rename = "isNotSerialized", skip_serializing_if = "Option::is_none")]
    pub is_not_serialized: Option<bool>,
    #[serde(rename = "isPinvokeImpl", skip_serializing_if = "Option::is_none")]
    pub is_pinvoke_impl: Option<bool>,
    #[serde(rename = "isSpecialName", skip_serializing_if = "Option::is_none")]
    pub is_special_name: Option<bool>,
    #[serde(rename = "isStatic", skip_serializing_if = "Option::is_none")]
    pub is_static: Option<bool>,
    #[serde(rename = "isAssembly", skip_serializing_if = "Option::is_none")]
    pub is_assembly: Option<bool>,
    #[serde(rename = "isFamily", skip_serializing_if = "Option::is_none")]
    pub is_family: Option<bool>,
    #[serde(rename = "isFamilyAndAssembly", skip_serializing_if = "Option::is_none")]
    pub is_family_and_assembly: Option<bool>,
    #[serde(rename = "isFamilyOrAssembly", skip_serializing_if = "Option::is_none")]
    pub is_family_or_assembly: Option<bool>,
    #[serde(rename = "isPrivate", skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[serde(rename = "isSecurityCritical", skip_serializing_if = "Option::is_none")]
    pub is_security_critical: Option<bool>,
    #[serde(rename = "isSecuritySafeCritical", skip_serializing_if = "Option::is_none")]
    pub is_security_safe_critical: Option<bool>,
    #[serde(rename = "isSecurityTransparent", skip_serializing_if = "Option::is_none")]
    pub is_security_transparent: Option<bool>,
    #[serde(rename = "fieldHandle", skip_serializing_if = "Option::is_none")]
    pub field_handle: Option<Box<crate::models::RuntimeFieldHandle>>,
}

impl FieldInfo {
    pub fn new() -> FieldInfo {
        FieldInfo {
            name: None,
            declaring_type: None,
            reflected_type: None,
            module: None,
            custom_attributes: None,
            is_collectible: None,
            metadata_token: None,
            member_type: None,
            attributes: None,
            field_type: None,
            is_init_only: None,
            is_literal: None,
            is_not_serialized: None,
            is_pinvoke_impl: None,
            is_special_name: None,
            is_static: None,
            is_assembly: None,
            is_family: None,
            is_family_and_assembly: None,
            is_family_or_assembly: None,
            is_private: None,
            is_public: None,
            is_security_critical: None,
            is_security_safe_critical: None,
            is_security_transparent: None,
            field_handle: None,
        }
    }
}


