/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GenericParameterAttributes {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Covariant")]
    Covariant,
    #[serde(rename = "Contravariant")]
    Contravariant,
    #[serde(rename = "VarianceMask")]
    VarianceMask,
    #[serde(rename = "ReferenceTypeConstraint")]
    ReferenceTypeConstraint,
    #[serde(rename = "NotNullableValueTypeConstraint")]
    NotNullableValueTypeConstraint,
    #[serde(rename = "DefaultConstructorConstraint")]
    DefaultConstructorConstraint,
    #[serde(rename = "SpecialConstraintMask")]
    SpecialConstraintMask,

}

impl ToString for GenericParameterAttributes {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::Covariant => String::from("Covariant"),
            Self::Contravariant => String::from("Contravariant"),
            Self::VarianceMask => String::from("VarianceMask"),
            Self::ReferenceTypeConstraint => String::from("ReferenceTypeConstraint"),
            Self::NotNullableValueTypeConstraint => String::from("NotNullableValueTypeConstraint"),
            Self::DefaultConstructorConstraint => String::from("DefaultConstructorConstraint"),
            Self::SpecialConstraintMask => String::from("SpecialConstraintMask"),
        }
    }
}

impl Default for GenericParameterAttributes {
    fn default() -> GenericParameterAttributes {
        Self::None
    }
}




