/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HealthStatus {
    #[serde(rename = "Unhealthy")]
    Unhealthy,
    #[serde(rename = "Degraded")]
    Degraded,
    #[serde(rename = "Healthy")]
    Healthy,

}

impl ToString for HealthStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Unhealthy => String::from("Unhealthy"),
            Self::Degraded => String::from("Degraded"),
            Self::Healthy => String::from("Healthy"),
        }
    }
}

impl Default for HealthStatus {
    fn default() -> HealthStatus {
        Self::Unhealthy
    }
}




