/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LayoutKind {
    #[serde(rename = "Sequential")]
    Sequential,
    #[serde(rename = "Explicit")]
    Explicit,
    #[serde(rename = "Auto")]
    Auto,

}

impl ToString for LayoutKind {
    fn to_string(&self) -> String {
        match self {
            Self::Sequential => String::from("Sequential"),
            Self::Explicit => String::from("Explicit"),
            Self::Auto => String::from("Auto"),
        }
    }
}

impl Default for LayoutKind {
    fn default() -> LayoutKind {
        Self::Sequential
    }
}




