/*
 * Fermyon Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LockedTrigger {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "triggerType", skip_serializing_if = "Option::is_none")]
    pub trigger_type: Option<String>,
    #[serde(rename = "triggerConfig", skip_serializing_if = "Option::is_none")]
    pub trigger_config: Option<::std::collections::HashMap<String, String>>,
}

impl LockedTrigger {
    pub fn new() -> LockedTrigger {
        LockedTrigger {
            id: None,
            trigger_type: None,
            trigger_config: None,
        }
    }
}


