/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MethodAttributes {
    #[serde(rename = "ReuseSlot")]
    ReuseSlot,
    #[serde(rename = "Private")]
    Private,
    #[serde(rename = "FamANDAssem")]
    FamAndAssem,
    #[serde(rename = "Assembly")]
    Assembly,
    #[serde(rename = "Family")]
    Family,
    #[serde(rename = "FamORAssem")]
    FamOrAssem,
    #[serde(rename = "Public")]
    Public,
    #[serde(rename = "MemberAccessMask")]
    MemberAccessMask,
    #[serde(rename = "UnmanagedExport")]
    UnmanagedExport,
    #[serde(rename = "Static")]
    Static,
    #[serde(rename = "Final")]
    Final,
    #[serde(rename = "Virtual")]
    Virtual,
    #[serde(rename = "HideBySig")]
    HideBySig,
    #[serde(rename = "NewSlot")]
    NewSlot,
    #[serde(rename = "CheckAccessOnOverride")]
    CheckAccessOnOverride,
    #[serde(rename = "Abstract")]
    Abstract,
    #[serde(rename = "SpecialName")]
    SpecialName,
    #[serde(rename = "RTSpecialName")]
    RtSpecialName,
    #[serde(rename = "PinvokeImpl")]
    PinvokeImpl,
    #[serde(rename = "HasSecurity")]
    HasSecurity,
    #[serde(rename = "RequireSecObject")]
    RequireSecObject,
    #[serde(rename = "ReservedMask")]
    ReservedMask,

}

impl ToString for MethodAttributes {
    fn to_string(&self) -> String {
        match self {
            Self::ReuseSlot => String::from("ReuseSlot"),
            Self::Private => String::from("Private"),
            Self::FamAndAssem => String::from("FamANDAssem"),
            Self::Assembly => String::from("Assembly"),
            Self::Family => String::from("Family"),
            Self::FamOrAssem => String::from("FamORAssem"),
            Self::Public => String::from("Public"),
            Self::MemberAccessMask => String::from("MemberAccessMask"),
            Self::UnmanagedExport => String::from("UnmanagedExport"),
            Self::Static => String::from("Static"),
            Self::Final => String::from("Final"),
            Self::Virtual => String::from("Virtual"),
            Self::HideBySig => String::from("HideBySig"),
            Self::NewSlot => String::from("NewSlot"),
            Self::CheckAccessOnOverride => String::from("CheckAccessOnOverride"),
            Self::Abstract => String::from("Abstract"),
            Self::SpecialName => String::from("SpecialName"),
            Self::RtSpecialName => String::from("RTSpecialName"),
            Self::PinvokeImpl => String::from("PinvokeImpl"),
            Self::HasSecurity => String::from("HasSecurity"),
            Self::RequireSecObject => String::from("RequireSecObject"),
            Self::ReservedMask => String::from("ReservedMask"),
        }
    }
}

impl Default for MethodAttributes {
    fn default() -> MethodAttributes {
        Self::ReuseSlot
    }
}




