/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParameterAttributes {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "In")]
    In,
    #[serde(rename = "Out")]
    Out,
    #[serde(rename = "Lcid")]
    Lcid,
    #[serde(rename = "Retval")]
    Retval,
    #[serde(rename = "Optional")]
    Optional,
    #[serde(rename = "HasDefault")]
    HasDefault,
    #[serde(rename = "HasFieldMarshal")]
    HasFieldMarshal,
    #[serde(rename = "Reserved3")]
    Reserved3,
    #[serde(rename = "Reserved4")]
    Reserved4,
    #[serde(rename = "ReservedMask")]
    ReservedMask,

}

impl ToString for ParameterAttributes {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::In => String::from("In"),
            Self::Out => String::from("Out"),
            Self::Lcid => String::from("Lcid"),
            Self::Retval => String::from("Retval"),
            Self::Optional => String::from("Optional"),
            Self::HasDefault => String::from("HasDefault"),
            Self::HasFieldMarshal => String::from("HasFieldMarshal"),
            Self::Reserved3 => String::from("Reserved3"),
            Self::Reserved4 => String::from("Reserved4"),
            Self::ReservedMask => String::from("ReservedMask"),
        }
    }
}

impl Default for ParameterAttributes {
    fn default() -> ParameterAttributes {
        Self::None
    }
}




