/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PropertyInfo {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "declaringType", skip_serializing_if = "Option::is_none")]
    pub declaring_type: Option<Box<crate::models::Type>>,
    #[serde(rename = "reflectedType", skip_serializing_if = "Option::is_none")]
    pub reflected_type: Option<Box<crate::models::Type>>,
    #[serde(rename = "module", skip_serializing_if = "Option::is_none")]
    pub module: Option<Box<crate::models::Module>>,
    #[serde(rename = "customAttributes", skip_serializing_if = "Option::is_none")]
    pub custom_attributes: Option<Vec<crate::models::CustomAttributeData>>,
    #[serde(rename = "isCollectible", skip_serializing_if = "Option::is_none")]
    pub is_collectible: Option<bool>,
    #[serde(rename = "metadataToken", skip_serializing_if = "Option::is_none")]
    pub metadata_token: Option<i32>,
    #[serde(rename = "memberType", skip_serializing_if = "Option::is_none")]
    pub member_type: Option<crate::models::MemberTypes>,
    #[serde(rename = "propertyType", skip_serializing_if = "Option::is_none")]
    pub property_type: Option<Box<crate::models::Type>>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<crate::models::PropertyAttributes>,
    #[serde(rename = "isSpecialName", skip_serializing_if = "Option::is_none")]
    pub is_special_name: Option<bool>,
    #[serde(rename = "canRead", skip_serializing_if = "Option::is_none")]
    pub can_read: Option<bool>,
    #[serde(rename = "canWrite", skip_serializing_if = "Option::is_none")]
    pub can_write: Option<bool>,
    #[serde(rename = "getMethod", skip_serializing_if = "Option::is_none")]
    pub get_method: Option<Box<crate::models::MethodInfo>>,
    #[serde(rename = "setMethod", skip_serializing_if = "Option::is_none")]
    pub set_method: Option<Box<crate::models::MethodInfo>>,
}

impl PropertyInfo {
    pub fn new() -> PropertyInfo {
        PropertyInfo {
            name: None,
            declaring_type: None,
            reflected_type: None,
            module: None,
            custom_attributes: None,
            is_collectible: None,
            metadata_token: None,
            member_type: None,
            property_type: None,
            attributes: None,
            is_special_name: None,
            can_read: None,
            can_write: None,
            get_method: None,
            set_method: None,
        }
    }
}


