/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PropertyAttributes {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "SpecialName")]
    SpecialName,
    #[serde(rename = "RTSpecialName")]
    RtSpecialName,
    #[serde(rename = "HasDefault")]
    HasDefault,
    #[serde(rename = "Reserved2")]
    Reserved2,
    #[serde(rename = "Reserved3")]
    Reserved3,
    #[serde(rename = "Reserved4")]
    Reserved4,
    #[serde(rename = "ReservedMask")]
    ReservedMask,

}

impl ToString for PropertyAttributes {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::SpecialName => String::from("SpecialName"),
            Self::RtSpecialName => String::from("RTSpecialName"),
            Self::HasDefault => String::from("HasDefault"),
            Self::Reserved2 => String::from("Reserved2"),
            Self::Reserved3 => String::from("Reserved3"),
            Self::Reserved4 => String::from("Reserved4"),
            Self::ReservedMask => String::from("ReservedMask"),
        }
    }
}

impl Default for PropertyAttributes {
    fn default() -> PropertyAttributes {
        Self::None
    }
}




