/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityRuleSet {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Level1")]
    Level1,
    #[serde(rename = "Level2")]
    Level2,

}

impl ToString for SecurityRuleSet {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::Level1 => String::from("Level1"),
            Self::Level2 => String::from("Level2"),
        }
    }
}

impl Default for SecurityRuleSet {
    fn default() -> SecurityRuleSet {
        Self::None
    }
}




