/*
 * Fermyon.Cloud.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StructLayoutAttribute {
    #[serde(rename = "typeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub type_id: Option<Option<serde_json::Value>>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::models::LayoutKind>,
}

impl StructLayoutAttribute {
    pub fn new() -> StructLayoutAttribute {
        StructLayoutAttribute {
            type_id: None,
            value: None,
        }
    }
}


